[package]
name = "advent-of-code-2019"
version = "0.1.0"
authors = ["Marcus Griep <marcus@griep.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
lazy_static = "1"
num-traits = "0.2"
thiserror = "1"
snafu = "0.6"

[dev-dependencies]
criterion = "0.3"
pretty_assertions = "0.6"

[features]
part-1 = []